### ISSUE TITLE
Hide / Show Layout Button is displayed multiple times

### ISSUE THREAD

**Issue by timohubois** [flyntwp/acf-hide-layout#1]
If flexible_content inside flexible_content is used then the "Hide / Show Layout Button" displayed multiple times.
 
<img width="1090" alt="flexible_conten_inside_ flexible_conten" src="https://user-images.githubusercontent.com/46505685/105349183-a2b1c900-5be9-11eb-9603-4586c4175b4c.png">

**Comment by mjot** [comment]
I can confirm this issue:

![CleanShot 2021-07-01 at 20 32 54@2x](https://user-images.githubusercontent.com/1445991/124173614-92145180-daab-11eb-8cf1-6659d9dd9486.png)

**Comment by mjot** [comment]
If you click on one of the hide / show buttons, all layouts are hidden:

![CleanShot 2021-07-01 at 20 44 31@2x](https://user-images.githubusercontent.com/1445991/124174937-3f3b9980-daad-11eb-8ba3-756250659936.png)

**Comment by mjot** [comment]
@harunbleech This problem is still persist.

**Comment by viktorbijlenga** [comment]
This issue also affects repeater fields.

**Comment by R3dRidl3** [comment]
@harunbleech 
Ah flex inside flex. Yeah I can confirm that too.

![image](https://user-images.githubusercontent.com/20893581/145968326-48398971-1a4c-4724-9028-91cb50153ce4.png)

**Comment by viktorbijlenga** [comment]
The data-index value of the acf-hide-layout icon seems a bit of. I’m not sure if it's relevant, but might be something to look into.

<img width="976" alt="20211214-haMKXR5k@2x" src="https://user-images.githubusercontent.com/4863995/145968668-93430041-e624-4071-b2e4-fe97fb044244.png">

**Comment by R3dRidl3** [comment]
I don't think it has anything to do with that.
It has to do with the JS that's adding the items.

I have reduced it by 1, so still 2 visible instead of 3 now.
In script.js change 
$controls = $el.find( '.acf-fc-layout-controls' ),
to
$controls = $el.find( '> .acf-fc-layout-controls' ),

**Comment by timohubois** [comment]
Fixed with the latest release. Thanks to @harunbleech 💪
