### ISSUE TITLE
acf is not defined

### ISSUE THREAD

**Issue by R3dRidle** [flyntwp/acf-hide-layout#3]
I get a 'Uncaught ReferenceError: acf is not defined' on non-edit pages.

Solution is to change 
add_action( 'admin_enqueue_scripts', [ $this, 'enqueue_scripts' ] );

To this:
add_action( 'acf/input/admin_enqueue_scripts', [ $this, 'enqueue_scripts' ] );

**Comment by harunbleech** [comment]
@R3dRidle the issue was that you customized the script.js and removed the check `if ( window.acf )`. With this check there are no errors.
