### ISSUE TITLE
Undefined index: acf_hide_layout in acf-hide-layout.php on line 346

### ISSUE THREAD

**Issue by mjot** [flyntwp/acf-hide-layout#5]
How to reproduce this error:

I create a new page with the default template, this default template has no field groups assigned.

If I now change the template to a template that has a field group with a flexible content field assigned to it and then create a layout, the hide / show layout icon is missing:

![image](https://user-images.githubusercontent.com/1445991/119121987-55762480-ba2e-11eb-97bf-38053f5dbb64.png)

When I then save the page I get the error:

`Undefined index: acf_hide_layout in acf-hide-layout.php on line 346`.

As soon as the page has been reloaded once, the hide / show icon is visible again and the error no longer occurs when saving.

The problem does not occur if I save once after changing the template, before creating the first flex layout.

I think the problem occurs accordingly only if the page is loaded without a field group, and then when changing the template subsequently the field groups become active without acf hide layout.

**Comment by harunbleech** [comment]
@mjot thanks for reporting the issue. It is solved [now](https://github.com/flyntwp/acf-hide-layout/commit/b9166e0b7ecb9f664545ea2682447e07804ee23c)

**Comment by mjot** [comment]
@harunbleech thanks for fixing, tried it out and it solved the problem.

Have a nice day.
